# Generated by Django 2.2.5 on 2021-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole', models.CharField(choices=[('AAPL', 'aapl'), ('AMZN', 'amzn'), ('GOOG', 'goog'), ('FB', 'fb'), ('TSLA', 'tsla'), ('BABA', 'baba'), ('TSM', 'tsm'), ('V', 'v'), ('JPM', 'jpm'), ('JNJ', 'jnj'), ('WMT', 'wmt'), ('MA', 'ma'), ('DIS', 'dis'), ('NVDA', 'nvda'), ('BAC', 'bac'), ('PG', 'pg'), ('UNH', 'unh'), ('PYPL', 'pypl'), ('HD', 'hd'), ('INTC', 'intc'), ('NFLEX', 'nflex'), ('CMCSA', 'cmcsa'), ('VZ', 'vz'), ('ADBE', 'adbe'), ('KO', 'ko'), ('CSCO', 'csco'), ('SAP', 'sap'), ('HDB', 'hdb'), ('UL', 'ul')], max_length=20)),
                ('date', models.DateField(blank=True)),
                ('open', models.DecimalField(decimal_places=25, max_digits=50)),
                ('high', models.DecimalField(decimal_places=25, max_digits=50)),
                ('low', models.DecimalField(decimal_places=25, max_digits=50)),
                ('close', models.DecimalField(decimal_places=25, max_digits=50)),
                ('volume', models.DecimalField(decimal_places=25, max_digits=50)),
                ('adjclose', models.DecimalField(decimal_places=25, max_digits=50)),
            ],
        ),
    ]
