# Generated by Django 2.2.5 on 2021-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='open',
            new_name='open_uni',
        ),
        migrations.AddField(
            model_name='stat',
            name='serial',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=2),
            preserve_default=False,
        ),
    ]
